name: Lint and Test

on: [push, pull_request]

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - run: rustup update
      - run: rustup component add rustfmt
      - uses: actions/checkout@v4
      - run: cargo fmt -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - run: rustup update
      - run: rustup component add clippy
      - uses: actions/checkout@v4
      - run: cargo clippy --all --all-targets --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - run: rustup update
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: cargo build --all-features
      - run: cargo test --verbose --all --all-features
        env:
          RUST_BACKTRACE: 1

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: crate-ci/typos@master
      - uses: actions/checkout@v4
